routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$proxy_url = getenv('PROXY_URL');

if (!empty($proxy_url)) {
    URL::forceScheme('https');
    URL::forceRootUrl($proxy_url);
}

// Route::get('/login', function () {
//     return view('welcome');
// });

Route::get('api/tagihan', 'ApiController@tagihan')->name('api.tagihan');
Route::get('api/laporan', 'ApiController@laporan')->name('api.laporan');
Route::post('api/create_tagihan', 'ApiController@create_tagihan')->name('api.create.tagihan');
Route::post('api/login', 'ApiController@login')->name('api.login');
Route::post('api/login_user', 'ApiController@login_user')->name('api.login.user');

Route::get('api/pelanggan_all', 'ApiController@pelanggan_all')->name('api.pelanggan.all');
Route::get('api/pelanggan/{id}', 'ApiController@pelanggan')->name('api.pelanggan');
Route::get('api/pelanggan/rekening/{rekening}', 'ApiController@pelanggan_by_rekening')->name('api.pelanggan.rekening');
Route::get('api/laporan/{id_pelanggan}', 'ApiController@laporan_user')->name('api.laporan.pelanggan');
Route::get('api/tagihan/{id_pelanggan}', 'ApiController@tagihan_user')->name('api.laporan.tagihan');
Route::get('api/grafik', 'ApiController@grafik')->name('api.tagihan.grafik');
Route::get('api/grafik_pendapatan', 'ApiController@grafik_pendapatan')->name('api.tagihan.grafik.pendapatan');

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

// Route::get('/home', function () {
//     return view('pages.index');
// })->name('home');


Auth::routes(['register' => false]);

Route::get('/', 'HomeController@index')->name('home');
Route::get('/userd', 'HomeController@indexd')->name('home');
Route::get('/tagihan/datapelanggan', 'TagihanController@datapelanggan')->name('tagihan.datapelanggan');

Route::get('/tagihan/pembayaran/{id}', 'TagihanController@pembayaran')->name('tagihan.pembayaran');
Route::post('/tagihan/pembayaran/asw/{id}', 'TagihanController@storepembayaran')->name('tagihan.pembayaran.store.asw');
Route::get('/tagihan/export/', 'TagihanController@export')->name('tagihan.export');
// Route::get('/datapribadi','PelangganCOntroller@datapribadi');


// Route::get('/tagihan/store', 'TagihanController@store')->name('tagihan.store');

Route::resource('pelanggan', 'PelangganController');
Route::resource('harga', 'HargaController');
Route::resource('tagihan', 'TagihanController')->except(['datapelanggan']);
Route::resource('laporan', 'LaporanController');

Route::group(['middleware' => ['auth']], function(){

// Registration Routes...
Route::get('/newuser', 'RegisterController@form')->name('newuser');
Route::post('/newuser', 'RegisterController@create');

// Registration Routes...
Route::get('/newpelanggan', 'RegisterController@formpelanggan')->name('newpelanggan');
Route::post('/newpelanggan', 'RegisterController@createpelanggan');

Route::get('/user', 'AdminController@index')->name('user');

//user
Route::get('/datapribadi', 'User\DataPribadiController@index')->name('datapribadi');
Route::get('/datapribadi/edit/{id}', 'User\DataPribadiController@edit')->name('datapribadi.edit');
Route::post('/datapribadi/edit/{id}', 'User\DataPribadiController@update')->name('datapribadi.edit.store');


Route::get('user/tagihan', 'User\TagihanController@index')->name('user.tagihan');

Route::get('user/laporan', 'User\LaporanController@index')->name('user.laporan');


});

app/Http/Controllers/LaporanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\Tagihan;
use App\Model\Transaksi;
use App\Model\Laporan;
use App\Model\Harga;

use App\Model\Pelanggan;
// use Barryvdh\DomPDF\Facade as PDF;
use Barryvdh\DomPDF\Facade as PDF;

class LaporanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        //
        $tahun = $request->query('tahun');
        $bulan = $request->query('bulan');
        if ($tahun && $bulan) {
            $show = Transaksi::with('pelanggan', 'tagihan')->whereMonth('tanggal_transaksi', $bulan)->whereYear('tanggal_transaksi', $tahun)->get();
        } else {
            $show = Transaksi::with('pelanggan', 'tagihan')->get();
        }


        $data = [
            'show' => $show,
        ];
        // dd($data);
        // return $show;
        // die;
        if ($tahun && $bulan) {
            return view('pages.admin.laporan.index')->with('list', $data)->with('bulan', $bulan)->with('tahun', $tahun);
        } else {
            return view('pages.admin.laporan.index')->with('list', $data)->with('bulan', false)->with('tahun', false);
        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Transaksi::where('id', $id)->first();

        // return view('pages.admin.invoice.index', compact('data'));
        $pdf = PDF::loadView('pages.admin.invoice.index', compact('data'))->setPaper('a4', 'landscape');

        return $pdf->stream($data->tanggal_transaksi.'_'.$data->pelanggan['rekening'].'_invoice.pdf');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function datapelanggan(Request $request)
    {
        $data = Pelanggan::where('rekening', $request->kode)->first();

        return $data;
    }
}

app/Http/Controllers/User/LaporanController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Pelanggan;
use App\Model\Tagihan;
// use App\Model\Transaksi;
use App\User;
use Illuminate\Support\Facades\Auth;

class LaporanController extends Controller
{
        //
        public function index()
        {
            //
            $id_pelanggan = Auth::user()->username;
            // dd($id_user);

            $pelanggan = pelanggan::where('rekening', $id_pelanggan)->first();

            $show = Tagihan::with('pelanggan', 'transaksi')->where('id_pelanggan', $pelanggan->id)->where('status_bayar', 1)->get();


            return view('pages.users.laporan.index')->with('list', $show);

        }
}

resources/views/pages/admin/laporan/index.blade.php
@extends('layouts.index')

@section('content')

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 stretch-card">
                <div class="card">
                    <div class="card-body">
                        <p class="card-title">Laporan Pembayaran</p>
                        <form method="GET" action="/laporan">
                            @csrf
                            <div class="form-group row">
                                <div class="col-md-2">
                                    @php
                                    $list_bulan = [
                                        '01' => 'Januari',
                                        '02' => 'Februari',
                                        '03' => 'Maret',
                                        '04' => 'April',
                                        '05' => 'Mei',
                                        '06' => 'Juni',
                                        '07' => 'Juli',
                                        '08' => 'Agustus',
                                        '09' => 'September',
                                        '10' => 'Oktober',
                                        '11' => 'November',
                                        '12' => 'Desember',
                                    ];
                                    @endphp
                                    <select name="bulan" id="bulan" required>
                                        @if ($bulan)
                                        <option value="{{ $bulan }}" hidden selected>{{ array_key_exists($bulan, $list_bulan) ? $list_bulan[$bulan]  : 'None' }}</option>
                                        @else
                                        <option value="" hidden selected>Pilih Bulan</option>
                                        @endif
                                        <option value="01">Januari</option>
                                        <option value="02">Februari</option>
                                        <option value="03">Maret</option>
                                        <option value="04">April</option>
                                        <option value="05">Mei</option>
                                        <option value="06">Juni</option>
                                        <option value="07">Juli</option>
                                        <option value="08">Agustus</option>
                                        <option value="09">September</option>
                                        <option value="10">Oktober</option>
                                        <option value="11">November</option>
                                        <option value="12">Desember</option>
                                    </select>
                                </div>
                                <div class="col-md-2">
                                    <select name="tahun" id="tahun" required>
                                        @if ($tahun)
                                        <option value="{{ $tahun }}" hidden selected>{{ $tahun }}</option>
                                        @else
                                        <option value="" hidden selected>Pilih Tahun</option>
                                        @endif
                                        <option value="2022">2022</option>
                                        <option value="2021">2021</option>
                                        <option value="2020">2020</option>
                                    </select>
                                </div>
                                <div class="col-md-2">
                                    <button type="submit" class="btn btn-primary">
                                        Filter
                                    </button>
                                </div>
                            </div>
                        </form>
                        <div class="table-responsive">
                            @if(session()->has('message'))
                            <div class="alert alert-success">
                                {{ session()->get('message') }}
                            </div>

                            @endif
                            <table id="tabel_laporan" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Tanggal</th>
                                        <th>Nomor Rekening</th>
                                        <th>Nama</th>
                                        <th>Tagihan</th>
                                        <th>Pembayaran</th>
                                        <th>Kembalian</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @if(count($list) > 0)
                                    @foreach($list['show'] as $list)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $list->tanggal_transaksi }}</td>
                                        <td>{{ $list->pelanggan->rekening }}</td>
                                        <td>{{ $list->pelanggan->nama }}</td>
                                        <td>{{ $list->tagihan->tagihan }}</td>
                                        <td>{{ $list->pembayaran }}</td>
                                        <td>{{ $list->kembalian }}</td>
                                        <td style="display: inline-flex">
                                            <button class="btn btn-small btn-warning" style="margin-right: 5px" onclick="window.location.
                                                href='{{ route('laporan.show', $list->id) }}'">Print
                                            </button>
                                        </td>
                                    </tr>
                                    @endforeach
                                    @else
                                    <tr>
                                        <td colspan=3>Tidak Ada Data</td>
                                    </tr>
                                    @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
        $(document).ready(function() {
            $('#tabel_laporan').DataTable();
        } );
</script>

@endsection

  {{-- <footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
      <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2017 <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap Dash</a>. All rights reserved.</span>
      <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
    </div>
  </footer> --}}
  <!-- partial -->