routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$proxy_url = getenv('PROXY_URL');

if (!empty($proxy_url)) {
    URL::forceScheme('https');
    URL::forceRootUrl($proxy_url);
}

// Route::get('/login', function () {
//     return view('welcome');
// });

Route::get('api/tagihan', 'ApiController@tagihan')->name('api.tagihan');
Route::get('api/laporan', 'ApiController@laporan')->name('api.laporan');
Route::post('api/create_tagihan', 'ApiController@create_tagihan')->name('api.create.tagihan');
Route::post('api/login', 'ApiController@login')->name('api.login');
Route::post('api/login_user', 'ApiController@login_user')->name('api.login.user');

Route::get('api/pelanggan_all', 'ApiController@pelanggan_all')->name('api.pelanggan.all');
Route::get('api/pelanggan/{id}', 'ApiController@pelanggan')->name('api.pelanggan');
Route::get('api/pelanggan/rekening/{rekening}', 'ApiController@pelanggan_by_rekening')->name('api.pelanggan.rekening');
Route::get('api/laporan/{id_pelanggan}', 'ApiController@laporan_user')->name('api.laporan.pelanggan');
Route::get('api/tagihan/{id_pelanggan}', 'ApiController@tagihan_user')->name('api.laporan.tagihan');
Route::get('api/grafik', 'ApiController@grafik')->name('api.tagihan.grafik');
Route::get('api/grafik_pendapatan', 'ApiController@grafik_pendapatan')->name('api.tagihan.grafik.pendapatan');

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

// Route::get('/home', function () {
//     return view('pages.index');
// })->name('home');


Auth::routes(['register' => false]);

Route::get('/', 'HomeController@index')->name('home');
Route::get('/userd', 'HomeController@indexd')->name('home');
Route::get('/tagihan/datapelanggan', 'TagihanController@datapelanggan')->name('tagihan.datapelanggan');

Route::get('/tagihan/pembayaran/{id}', 'TagihanController@pembayaran')->name('tagihan.pembayaran');
Route::post('/tagihan/pembayaran/asw/{id}', 'TagihanController@storepembayaran')->name('tagihan.pembayaran.store.asw');
Route::get('/tagihan/export/', 'TagihanController@export')->name('tagihan.export');
// Route::get('/datapribadi','PelangganCOntroller@datapribadi');


// Route::get('/tagihan/store', 'TagihanController@store')->name('tagihan.store');

Route::resource('pelanggan', 'PelangganController');
Route::resource('harga', 'HargaController');
Route::resource('tagihan', 'TagihanController')->except(['datapelanggan']);
Route::resource('laporan', 'LaporanController');

Route::group(['middleware' => ['auth']], function(){

// Registration Routes...
Route::get('/newuser', 'RegisterController@form')->name('newuser');
Route::post('/newuser', 'RegisterController@create');

// Registration Routes...
Route::get('/newpelanggan', 'RegisterController@formpelanggan')->name('newpelanggan');
Route::post('/newpelanggan', 'RegisterController@createpelanggan');

Route::get('/user', 'AdminController@index')->name('user');

//user
Route::get('/datapribadi', 'User\DataPribadiController@index')->name('datapribadi');
Route::get('/datapribadi/edit/{id}', 'User\DataPribadiController@edit')->name('datapribadi.edit');
Route::post('/datapribadi/edit/{id}', 'User\DataPribadiController@update')->name('datapribadi.edit.store');


Route::get('user/tagihan', 'User\TagihanController@index')->name('user.tagihan');

Route::get('user/laporan', 'User\LaporanController@index')->name('user.laporan');


});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','username','email', 'password','status',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function Pelanggan()
    {
        return $this->hasMany('App\Pelanggan','rekening','id');
    }
}

app/Http/Controllers/User/DataPribadiController.php
<?php

namespace App\Http\Controllers\User;


use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Pelanggan;
use App\User;
use Illuminate\Support\Facades\Auth;

class DataPribadiController extends Controller
{
    //
    public function index()
    {
        //
        $id_user = Auth::id();
        $id_pelanggan = Auth::user()->username;
        // dd($id_user);

        $pelanggan = Pelanggan::where('rekening', $id_pelanggan)->first();
        $user = User::where('id', $id_user)->first();


        return view('pages.users.datapribadi.index', compact('pelanggan', 'user'));
    }

    public function edit($id)
    {
        
        //
        $list = Pelanggan::find($id);
        $user = User::where('username', $list->rekening)->first();

        return view('pages.users.datapribadi.edit', compact('user', 'list'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        // dd($request);
        $this->validate($request,[
            // 'rekening' => 'required',
            'nama' => 'required',
            'alamat' => 'required',
            'hp' => 'required',
            'email' => 'required',
            ]);
        $data = Pelanggan::find($id);
        $data->nama = $request->nama;
        $data->alamat = $request->alamat;
        $data->hp = $request->hp;
        $data->save();

        $user = User::where('username', $data->rekening)->first();
        $user->name = $request->nama;
        $user->email = $request->email;
        $user->save();

        return redirect('/datapribadi')->with('message','Perubahan Data Berhasil');
    }
}

app/Http/Controllers/User/LaporanController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Pelanggan;
use App\Model\Tagihan;
// use App\Model\Transaksi;
use App\User;
use Illuminate\Support\Facades\Auth;

class LaporanController extends Controller
{
        //
        public function index()
        {
            //
            $id_pelanggan = Auth::user()->username;
            // dd($id_user);

            $pelanggan = pelanggan::where('rekening', $id_pelanggan)->first();

            $show = Tagihan::with('pelanggan', 'transaksi')->where('id_pelanggan', $pelanggan->id)->where('status_bayar', 1)->get();


            return view('pages.users.laporan.index')->with('list', $show);

        }
}

app/Http/Controllers/User/TagihanController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Pelanggan;
use App\Model\Tagihan;
use App\User;
use Illuminate\Support\Facades\Auth;

class TagihanController extends Controller
{
    //
    public function index()
    {
        //
        $id_pelanggan = Auth::user()->username;
        // dd($id_user);

        $pelanggan = pelanggan::where('rekening', $id_pelanggan)->first();

        $show = Tagihan::with('pelanggan')->where('id_pelanggan', $pelanggan->id)->where('status_bayar', 0)->get();


        return view('pages.users.tagihan.index')->with('list', $show);

    }
}

resources/views/pages/admin/user/register.blade.php
@extends('layouts.index')

@section('content')

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 stretch-card">
                <div class="card">
                    <div class="card-body">

                        <form method="POST" action="{{ route('newuser') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="username" class="col-md-4 col-form-label text-md-right">{{ __('Username') }}</label>

                                <div class="col-md-6">
                                    <input id="username" type="text" class="form-control @error('username') is-invalid @enderror" name="username" value="{{ old('username') }}" required autocomplete="username" autofocus>

                                    @error('username')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                                    @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                    @error('password')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Register') }}
                                    </button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
        $(document).ready(function() {
            $('#tabelpelanggan').DataTable();
        } );
</script>

@endsection

  {{-- <footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
      <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2017 <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap Dash</a>. All rights reserved.</span>
      <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
    </div>
  </footer> --}}
  <!-- partial -->

resources/views/pages/admin/user/registerpelanggan.blade.php
@extends('layouts.index')

@section('content')

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 stretch-card">
                <div class="card">
                    <div class="card-body">

                        <form method="POST" action="{{ route('newpelanggan') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="username" class="col-md-4 col-form-label text-md-right">{{ __('Username') }}</label>

                                <div class="col-md-6">
                                    <input id="username" type="text" class="form-control @error('username') is-invalid @enderror" name="username" value="{{ $username }}" readonly autocomplete="username" autofocus>

                                    @error('username')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="alamat" class="col-md-4 col-form-label text-md-right">{{ __('Alamat') }}</label>

                                <div class="col-md-6">
                                    <input id="alamat" type="text" class="form-control @error('alamat') is-invalid @enderror" name="alamat" value="{{ old('alamat') }}" required autocomplete="alamat" autofocus>

                                    @error('alamat')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="hp" class="col-md-4 col-form-label text-md-right">{{ __('Nomor Hp') }}</label>

                                <div class="col-md-6">
                                    <input id="hp" type="text" oninput="this.value = this.value.replace(/[^0-9]/g, '').replace(/(\..*)\./g, '$1');" class="form-control @error('hp') is-invalid @enderror" name="hp" value="{{ old('hp') }}" required autocomplete="hp" autofocus>

                                    @error('hp')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Nama') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="meteran" class="col-md-4 col-form-label text-md-right">{{ __('Meteran') }}</label>

                                <div class="col-md-6">
                                    <input id="meteran" type="number" min="0" class="form-control @error('meteran') is-invalid @enderror" name="meteran" value="{{ old('meteran') }}" required autocomplete="meteran" autofocus>

                                    @error('meteran')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Email') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                                    @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                    @error('password')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Register') }}
                                    </button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
        $(document).ready(function() {
            $('#tabelpelanggan').DataTable();
        } );
</script>

@endsection

  {{-- <footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
      <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2017 <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap Dash</a>. All rights reserved.</span>
      <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
    </div>
  </footer> --}}
  <!-- partial -->

resources/views/pages/admin/user/user.blade.php
@extends('layouts.index')

@section('content')

<div class="main-panel">
    <div class="content-wrapper">
        <button class="btn btn-gradient-success mt-4" onclick="window.location.href='{{ route('pelanggan.create') }}'">+ Tambah Pelanggan</button> <br><br>
        <div class="row">
            <div class="col-md-12 stretch-card">
                <div class="card">
                    <div class="card-body">
                        <p class="card-title">Tabel Pelanggan</p>
                        <div class="table-responsive">
                            @if(session()->has('message'))
                            <div class="alert alert-success">
                                {{ session()->get('message') }}
                            </div>

                            @endif
                            <table id="tabel_user" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>No</th>

                                        <th>Nomor Rekening</th>

                                        <th>Nama</th>
                                        <th>Alamat</th>
                                        <th>Nomor HP</th>
                                        <th>Meteran</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @if(count($list) > 0)
                                    @foreach($list['show'] as $list)
                                    <tr>
                                        <td>{{ $list->id }}</td>
                                        <td>{{ $list->rekening }}</td>
                                        <td>{{ $list->nama }}</td>
                                        <td>{{ $list->alamat }}</td>
                                        <td>{{ $list->hp }}</td>
                                        <td>{{ $list->meteran }}</td>
                                        <td style="display: inline-flex">
                                            <button class="btn btn-small btn-warning" style="margin-right: 5px" onclick="window.location.
                                                href='{{ route('pelanggan.edit', $list->id) }}'">Ubah
                                            </button>
                                            <form action="{{ route('pelanggan.destroy', $list->id) }}" method="POST">
                                                @method('DELETE')
                                                @csrf
                                                <button class="btn btn-small btn-primary">Hapus</button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                    @else
                                    <tr>
                                        <td colspan=3>Tidak Ada Data</td>
                                    </tr>
                                    @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
        $(document).ready(function() {
            $('#tabel_user').DataTable();
        } );
</script>

@endsection

  {{-- <footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
      <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2017 <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap Dash</a>. All rights reserved.</span>
      <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
    </div>
  </footer> --}}
  <!-- partial -->