routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$proxy_url = getenv('PROXY_URL');

if (!empty($proxy_url)) {
    URL::forceScheme('https');
    URL::forceRootUrl($proxy_url);
}

// Route::get('/login', function () {
//     return view('welcome');
// });

Route::get('api/tagihan', 'ApiController@tagihan')->name('api.tagihan');
Route::get('api/laporan', 'ApiController@laporan')->name('api.laporan');
Route::post('api/create_tagihan', 'ApiController@create_tagihan')->name('api.create.tagihan');
Route::post('api/login', 'ApiController@login')->name('api.login');
Route::post('api/login_user', 'ApiController@login_user')->name('api.login.user');

Route::get('api/pelanggan_all', 'ApiController@pelanggan_all')->name('api.pelanggan.all');
Route::get('api/pelanggan/{id}', 'ApiController@pelanggan')->name('api.pelanggan');
Route::get('api/pelanggan/rekening/{rekening}', 'ApiController@pelanggan_by_rekening')->name('api.pelanggan.rekening');
Route::get('api/laporan/{id_pelanggan}', 'ApiController@laporan_user')->name('api.laporan.pelanggan');
Route::get('api/tagihan/{id_pelanggan}', 'ApiController@tagihan_user')->name('api.laporan.tagihan');
Route::get('api/grafik', 'ApiController@grafik')->name('api.tagihan.grafik');
Route::get('api/grafik_pendapatan', 'ApiController@grafik_pendapatan')->name('api.tagihan.grafik.pendapatan');

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

// Route::get('/home', function () {
//     return view('pages.index');
// })->name('home');


Auth::routes(['register' => false]);

Route::get('/', 'HomeController@index')->name('home');
Route::get('/userd', 'HomeController@indexd')->name('home');
Route::get('/tagihan/datapelanggan', 'TagihanController@datapelanggan')->name('tagihan.datapelanggan');

Route::get('/tagihan/pembayaran/{id}', 'TagihanController@pembayaran')->name('tagihan.pembayaran');
Route::post('/tagihan/pembayaran/asw/{id}', 'TagihanController@storepembayaran')->name('tagihan.pembayaran.store.asw');
Route::get('/tagihan/export/', 'TagihanController@export')->name('tagihan.export');
// Route::get('/datapribadi','PelangganCOntroller@datapribadi');


// Route::get('/tagihan/store', 'TagihanController@store')->name('tagihan.store');

Route::resource('pelanggan', 'PelangganController');
Route::resource('harga', 'HargaController');
Route::resource('tagihan', 'TagihanController')->except(['datapelanggan']);
Route::resource('laporan', 'LaporanController');

Route::group(['middleware' => ['auth']], function(){

// Registration Routes...
Route::get('/newuser', 'RegisterController@form')->name('newuser');
Route::post('/newuser', 'RegisterController@create');

// Registration Routes...
Route::get('/newpelanggan', 'RegisterController@formpelanggan')->name('newpelanggan');
Route::post('/newpelanggan', 'RegisterController@createpelanggan');

Route::get('/user', 'AdminController@index')->name('user');

//user
Route::get('/datapribadi', 'User\DataPribadiController@index')->name('datapribadi');
Route::get('/datapribadi/edit/{id}', 'User\DataPribadiController@edit')->name('datapribadi.edit');
Route::post('/datapribadi/edit/{id}', 'User\DataPribadiController@update')->name('datapribadi.edit.store');


Route::get('user/tagihan', 'User\TagihanController@index')->name('user.tagihan');

Route::get('user/laporan', 'User\LaporanController@index')->name('user.laporan');


});

app/Http/Controllers/HargaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\Harga;

class HargaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $show = harga::all();
        $data = [
            'show' => $show,
        ];
        return view('pages.admin.harga.index')->with('list', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('pages.admin.harga.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[
            'harga_pakai' => 'required',
            'harga_beban' => 'required',
            ]);
        $data = new harga;
        $data->harga_pakai = $request->harga_pakai;
        $data->harga_beban = $request->harga_beban;
        $data->save();

        return redirect('/harga')->with('message','Tambah Data Berhasil');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $data = harga::find($id);
        return view('pages.admin.harga.edit')->with('list', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request,[
            'harga_pakai' => 'required',
            'harga_beban' => 'required',
            ]);
        $data = harga::find($id);
        $data->harga_pakai = $request->harga_pakai;
        $data->harga_beban = $request->harga_beban;
        $data->save();

        return redirect('/harga')->with('message','Perubahan Data Berhasil');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $data = harga::find($id);
        $data->delete();
        // redirect
        return redirect('/harga')->with('message','Hapus Data harga Berhasil');
    }
}

resources/views/pages/admin/harga/create.blade.php
@extends('layouts.index')

@section('content')


<div class="main-panel">
  <div class="content-wrapper">
    <div class="card">
      <div class="card-body">
        <p class="card-title">Tambah Harga</p>
        <table class="table table-bordered"></table>
        <form action="{{ route('harga.store') }}" method="POST">{{ csrf_field() }}
          <div class="form-group">
            <Label>Harga Pakai</Label>
            <input type="text" class="form-control" name="harga_pakai" placeholder="Harga Pakai">
          </div>
          <div class="form-group">
            <Label>Harga Beban</Label>
            <input type="text" class="form-control" name="harga_beban" placeholder="Harga Beban">
          </div>
          <button class="btn btn-success">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>

@endsection

    {{-- <footer class="footer">
      <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2017 <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap Dash</a>. All rights reserved.</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
      </div>
    </footer> --}}

resources/views/pages/admin/harga/edit.blade.php
@extends('layouts.index')

@section('content')
<div class="main-panel">
  <div class="content-wrapper">
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
              <div class="col-md-12">
                  <div class="card">  
                      <div class="card-body">
                          <h4 class="card-title"><i class="mdi mdi-account-plus mr-3 icon-sm text-success"></i>Ubah Data Harga #{{ $list->id }}</h4>
                          <form action="{{url('pelanggan', [$list->id])}}" method="POST">
                              {{method_field('PUT')}}
                              {{ csrf_field() }}
                              <div class="form-group">
                                <Label>Harga Pakai</Label>
                                <input type="text" class="form-control" name="harga_pakai" value="{{ $list->harga_pakai }}" placeholder="{{ $list->harga_pakai }}">
                              </div>
                              <div class="form-group">
                                <Label>Harga Beban</Label>
                                <input type="text" class="form-control" name="harga_beban" value="{{ $list->harga_beban }}" placeholder="{{ $list->harga_beban }}">
                              </div>
                              <button class="btn btn-success">Submit</button>
                          </form>
                      </div>
                  </div>
              </div>
            </div>
        </div>
      </div>
  </div>
  <!-- content-wrapper ends -->
  <!-- partial:partials/_footer.html -->
  <footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
      <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2017 <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap Dash</a>. All rights reserved.</span>
      <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
    </div>
  </footer>
  <!-- partial -->
</div>
<!-- main-panel ends -->

@endsection

resources/views/pages/admin/harga/index.blade.php
@extends('layouts.index')

@section('content')

<div class="main-panel">
    <div class="content-wrapper">
        {{-- <button class="btn btn-gradient-success mt-4" onclick="window.location.href='{{ route('harga.create') }}'">+ Tambah Harga</button> <br><br> --}}
        <div class="row">
            <div class="col-md-12 stretch-card">
                <div class="card">
                    <div class="card-body">
                        <p class="card-title">Tabel Harga</p>
                        <div class="table-responsive">
                            @if(session()->has('message'))
                            <div class="alert alert-success">
                                {{ session()->get('message') }}
                            </div>

                            @endif
                            <table id="tabel_harga" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Harga Pakai</th>
                                        <th>Harga Beban</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @if(count($list) > 0)
                                    @foreach($list['show'] as $list)
                                    <tr>
                                        <td>{{ $list->id }}</td>
                                        <td>{{ $list->harga_pakai }}</td>
                                        <td>{{ $list->harga_beban }}</td>
                                        <td style="display: inline-flex">
                                            <button class="btn btn-small btn-warning" style="margin-right: 5px" onclick="window.location.
                                                href='{{ route('harga.edit', $list->id) }}'">Ubah
                                            </button>
                                        </td>
                                    </tr>
                                    @endforeach
                                    @else
                                    <tr>
                                        <td colspan=3>Tidak Ada Data</td>
                                    </tr>
                                    @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
        $(document).ready(function() {
            $('#tabel_harga').DataTable();
        } );
</script>

@endsection

  {{-- <footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
      <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2017 <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap Dash</a>. All rights reserved.</span>
      <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
    </div>
  </footer> --}}
  <!-- partial -->